# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(489, 297)
        Dialog.setStyleSheet("")
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(40, 240, 411, 51))
        self.button_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_box.setStyleSheet("background-color:rgb(135, 135, 135)")
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.image_label = QtWidgets.QLabel(Dialog)
        self.image_label.setGeometry(QtCore.QRect(30, 20, 191, 191))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(-10, 0, 511, 301))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../../../Downloads/WhatsApp Image 2022-07-25 at 23.23.48.jpeg"))
        self.background.setObjectName("background")
        self.comment_label = QtWidgets.QLabel(Dialog)
        self.comment_label.setGeometry(QtCore.QRect(250, 30, 239, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comment_label.setFont(font)
        self.comment_label.setStyleSheet("color: rgb(202, 202, 202)")
        self.comment_label.setObjectName("comment_label")
        self.cpm_label = QtWidgets.QLabel(Dialog)
        self.cpm_label.setGeometry(QtCore.QRect(250, 80, 239, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cpm_label.setFont(font)
        self.cpm_label.setStyleSheet("color:rgb(202, 202, 202)")
        self.cpm_label.setObjectName("cpm_label")
        self.time_label = QtWidgets.QLabel(Dialog)
        self.time_label.setGeometry(QtCore.QRect(250, 120, 239, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color:rgb(202, 202, 202)")
        self.time_label.setObjectName("time_label")
        self.background.raise_()
        self.button_box.raise_()
        self.image_label.raise_()
        self.comment_label.raise_()
        self.cpm_label.raise_()
        self.time_label.raise_()

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept)
        self.button_box.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Результат"))
        self.comment_label.setText(_translate("Dialog", "Отличный результат!"))
        self.cpm_label.setText(_translate("Dialog", "Символов в минуту: 250"))
        self.time_label.setText(_translate("Dialog", "Общее время:1:20"))
